### ISSUE TITLE
Doesn't cause problems during a regional.

### ISSUE THREAD

**Issue by auxiliary-character** [DenfeldRobotics4009/2016_Freckles#3]
As stated in the title, the robot made it through a whole regional without crashing, setpoints slipping, or any other similar programming problems.

This is a difficult issue to observe; it doesn't happen very often. I hope it can be reproduced and debugged in the upcoming Idaho regional.

(Nice job, Nik. [;)](https://xkcd.com/541/))

**Comment by nikolojedison** [comment]
This issue is occurring only in an internal development release and will be updated to "Feature" status upon release.

**Comment by nikolojedison** [comment]
See [https://github.com/DenfeldRobotics4009/2016_Freckles/releases/tag/1.0.1](url)
